### ISSUE TITLE
BUG : Name

### ISSUE THREAD

**Issue by nehadhyani** [Anupam-Panwar/Grading-System-automation#37]
**Describe the bug**
Login page not responsive for galaxy fold

**Expected behavior**
Login page should be responsive

**Screenshots**
![image](https://user-images.githubusercontent.com/79048617/114744949-d5dca200-9d6b-11eb-99fb-3e2d3f346185.png)

**Comment by PriyanshuUpadhyay** [comment]
Bug fixed! pr sent
